// Generated by IcedCoffeeScript 1.3.1c
(function() {
  var Future;

  Future = function() {
    var callback, future, result;
    callback = null;
    result = null;
    future = function(cb) {
      if (result) {
        return cb.apply(null, result);
      } else {
        return callback = cb;
      }
    };
    future.toString = function() {
      return '[Future]';
    };
    future.inspect = future.toString;
    future.resolve = function() {
      if (callback) {
        return callback.apply(null, arguments);
      } else {
        return result = arguments;
      }
    };
    return future;
  };

  module.exports = Future;

}).call(this);
